import {
  createUserWithEmailAndPassword,
  onAuthStateChanged,
  signInWithCustomToken,
  signInWithEmailAndPassword,
  signOut,
  type User,
} from 'firebase/auth';
import {
  collection,
  doc,
  getDoc,
  getDocs,
  increment,
  limit,
  onSnapshot,
  query,
  serverTimestamp,
  setDoc,
  Timestamp,
  type Unsubscribe,
  where,
} from 'firebase/firestore';
import { auth, db } from './firebase';

/** A contact is shown as "online" if their last heartbeat was within this window. Same value as the mobile app. */
export const ONLINE_THRESHOLD_MS = 60_000;

export interface UserProfile {
  photoUrl?: string;
  videoBytesUsed: number;
}

export interface Account {
  uid: string;
  username: string;
  /** 'admin' for the single, openly disclosed admin account (see src/config/adminConfig.ts's ADMIN_UID and ObsidianVault/Changelog.md) — routes to AdminScreen instead of the normal contacts/chat UI. Undefined for every regular account. */
  role?: string;
}

// Same synthetic-email scheme as the mobile app's userService.ts — a
// username maps to `${username}@gizlichat.local` so the same account works
// interchangeably from the phone and the browser.
const USERNAME_EMAIL_DOMAIN = '@gizlichat.local';
const USERNAME_PATTERN = /^[a-zA-Z0-9_]{3,20}$/;

function usernameToEmail(username: string): string {
  return `${username.trim().toLowerCase()}${USERNAME_EMAIL_DOMAIN}`;
}

export function validateUsername(username: string): string | null {
  if (!USERNAME_PATTERN.test(username.trim())) {
    return 'Kullanıcı adı 3-20 karakter olmalı, sadece harf/rakam/_ içerebilir.';
  }
  return null;
}

function mapAuthError(error: unknown): string {
  const code = (error as { code?: string }).code ?? '';
  switch (code) {
    case 'auth/email-already-in-use':
      return 'Bu kullanıcı adı zaten alınmış.';
    case 'auth/weak-password':
      return 'Şifre en az 6 karakter olmalı.';
    case 'auth/user-not-found':
    case 'auth/wrong-password':
    case 'auth/invalid-credential':
      return 'Kullanıcı adı veya şifre hatalı.';
    case 'auth/invalid-email':
      return 'Geçersiz kullanıcı adı.';
    default:
      return (error as Error).message ?? 'Beklenmeyen bir hata oluştu.';
  }
}

export async function registerAccount(username: string, password: string): Promise<Account> {
  const cleanUsername = username.trim();
  const usernameError = validateUsername(cleanUsername);
  if (usernameError) {
    throw new Error(usernameError);
  }
  try {
    const credential = await createUserWithEmailAndPassword(auth, usernameToEmail(cleanUsername), password);
    await setDoc(doc(db, 'users', credential.user.uid), {
      username: cleanUsername,
      usernameLower: cleanUsername.toLowerCase(),
      createdAt: Date.now(),
    });
    return { uid: credential.user.uid, username: cleanUsername };
  } catch (error) {
    throw new Error(mapAuthError(error));
  }
}

export async function loginAccount(username: string, password: string): Promise<Account> {
  const cleanUsername = username.trim();
  try {
    const credential = await signInWithEmailAndPassword(auth, usernameToEmail(cleanUsername), password);
    const snap = await getDoc(doc(db, 'users', credential.user.uid));
    const data = snap.exists() ? snap.data() : undefined;
    const savedUsername = typeof data?.username === 'string' ? (data.username as string) : cleanUsername;
    const role = typeof data?.role === 'string' ? (data.role as string) : undefined;
    return { uid: credential.user.uid, username: savedUsername, role };
  } catch (error) {
    throw new Error(mapAuthError(error));
  }
}

export async function logoutAccount(): Promise<void> {
  await signOut(auth);
}

/**
 * Signs in without a password using a one-time custom token generated by an
 * admin via `scripts/generateLoginToken.js` (Firebase Admin SDK). Used as a
 * "forgot password" recovery path — the account's actual password is never
 * touched or seen. The token expires ~1 hour after generation.
 */
export async function loginWithRecoveryToken(token: string): Promise<Account> {
  try {
    const credential = await signInWithCustomToken(auth, token.trim());
    const snap = await getDoc(doc(db, 'users', credential.user.uid));
    const data = snap.exists() ? snap.data() : undefined;
    const savedUsername = typeof data?.username === 'string' ? (data.username as string) : credential.user.uid;
    const role = typeof data?.role === 'string' ? (data.role as string) : undefined;
    return { uid: credential.user.uid, username: savedUsername, role };
  } catch (error) {
    throw new Error('Kurtarma kodu geçersiz veya süresi dolmuş.');
  }
}

/** Resolves once Firebase Auth has restored any persisted browser session, without ever triggering a sign-in. */
export function watchAuthState(onUser: (user: User | null) => void): Unsubscribe {
  return onAuthStateChanged(auth, onUser);
}

export async function fetchAccountUsername(uid: string): Promise<string | null> {
  const snap = await getDoc(doc(db, 'users', uid));
  if (!snap.exists()) {
    return null;
  }
  const data = snap.data();
  return typeof data.username === 'string' ? data.username : null;
}

/** Looks up the `role` field written on this account's users/{uid} doc — only the single admin account (see ADMIN_UID) has one, written by scripts/createAdminAccount.js. */
export async function fetchAccountRole(uid: string): Promise<string | undefined> {
  const snap = await getDoc(doc(db, 'users', uid));
  if (!snap.exists()) {
    return undefined;
  }
  const data = snap.data();
  return typeof data.role === 'string' ? data.role : undefined;
}

/** Stamps this device's account as "recently active" — same cheap presence heartbeat as the mobile app. */
export async function updatePresenceHeartbeat(uid: string): Promise<void> {
  await setDoc(doc(db, 'users', uid), { lastActiveAt: serverTimestamp() }, { merge: true });
}

export function subscribeToPresence(uid: string, onLastActiveAt: (lastActiveAt: number | null) => void): Unsubscribe {
  return onSnapshot(
    doc(db, 'users', uid),
    snap => {
      const data = snap.data();
      const lastActiveAt = data?.lastActiveAt;
      onLastActiveAt(lastActiveAt instanceof Timestamp ? lastActiveAt.toMillis() : null);
    },
    () => onLastActiveAt(null),
  );
}

export function subscribeToUserProfile(uid: string, onProfile: (profile: UserProfile) => void): Unsubscribe {
  return onSnapshot(
    doc(db, 'users', uid),
    snap => {
      const data = snap.data();
      onProfile({
        photoUrl: typeof data?.photoUrl === 'string' ? data.photoUrl : undefined,
        videoBytesUsed: typeof data?.videoBytesUsed === 'number' ? data.videoBytesUsed : 0,
      });
    },
    () => onProfile({ videoBytesUsed: 0 }),
  );
}

export async function updateProfilePhoto(uid: string, dataUri: string | null): Promise<void> {
  await setDoc(doc(db, 'users', uid), { photoUrl: dataUri }, { merge: true });
}

export async function addVideoBytesUsed(uid: string, bytes: number): Promise<void> {
  await setDoc(doc(db, 'users', uid), { videoBytesUsed: increment(bytes) }, { merge: true });
}

export async function findUserByUsername(username: string): Promise<Account | null> {
  const cleanUsername = username.trim().toLowerCase();
  if (!cleanUsername) {
    return null;
  }
  const usersQuery = query(collection(db, 'users'), where('usernameLower', '==', cleanUsername), limit(1));
  const snapshot = await getDocs(usersQuery);
  if (snapshot.empty) {
    return null;
  }
  const found = snapshot.docs[0];
  const data = found.data();
  return { uid: found.id, username: typeof data.username === 'string' ? data.username : cleanUsername };
}
